name = "game_of_life"
uuid = "6dfc342f-5ad7-4a44-9d89-98a1de06532d"
authors = ["sof202 <s.o.fletcher@exeter.ac.uk>"]
version = "0.1.0"

[deps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
UnicodePlots = "3.8.0"
